module.exports.REQUEST_COMAND = {
  TIMER: "ARLARM",
  CONTROL: "RELAY",
  UPDATE_FIRMWARE: "update-firmware",
  SCAN_WIFI: "wifi_scan",
  CONNECT_WIFT: "wifi_connect",
  CHANGE_SERVER: "CHANGE_SERVER",
  RESTART: "RESTART",
  CHANGE_EM: "ENERGY",
};

module.exports.RESPONSE_COMAND = {
  INFOR_EM: "SYS_INFO",
  NEWSCAST: "SYS_BEAT",
  TIMER: "SYS_ARLARM",
  SCAN_WIFI: "WIFI_NETWORK",
  CONNECT_WIFT: "SYS_CONNECT",
  CHANGE_SERVER: "SYS_SERVER",
  RESTART: "SYS_RESTART",
  CHANGE_EM: "SYS_ENERGY",
};
