module.exports.REQUEST_COMAND_MQTT = {
  TIMER: "ARLARM",
  CONTROL: "RELAY",
  UPDATE_FIRMWARE: "update-firmware",
  SCAN_WIFI: "wifi_scan",
  CONNECT_WIFT: "wifi_connect",
  CHANGE_SERVER: "CHANGE_SERVER",
  RESTART: "RESTART",
  CHANGE_EM: "ENERGY",
};

module.exports.RESPONSE_COMAND_MQTT = {
  INFOR_EM: "SYS_INFO",
  NEWSCAST: "SYS_BEAT",
  TIMER: "SYS_ARLARM",
  SCAN_WIFI: "WIFI_NETWORK",
  CONNECT_WIFT: "SYS_CONNECT",
  CHANGE_SERVER: "SYS_SERVER",
  RESTART: "SYS_RESTART",
  CHANGE_EM: "SYS_ENERGY",
};

module.exports.REQUEST_COMAND_SOCKET = {
  ADD_TIMER: "ADD_TIMER",
  UPDATE_TIMER: "UPDATE_TIMER",
  DELETE_TIMER: "DELETE_TIMERS",
};
module.exports.RESPONSE_COMAND_SOCKET = {
  TIMER: "SYS_TIMER",
};
