module.exports.REQUEST_COMAND_MQTT = {
  TIMER: "ARLARM",
  CONTROL: "RELAY",
  UPDATE_FIRMWARE: "update-firmware",
  SCAN_WIFI: "wifi_scan",
  CONNECT_WIFT: "wifi_connect",
  CHANGE_SERVER: "CHANGE_SERVER",
  RESTART: "RESTART",
  CHANGE_EM: "ENERGY",
};

module.exports.RESPONSE_COMAND_MQTT = {
  INFOR_EM: "SYS_INFO",
  NEWSCAST: "SYS_BEAT",
  TIMER: "SYS_ARLARM",
  SCAN_WIFI: "WIFI_NETWORK",
  CONNECT_WIFT: "SYS_CONNECT",
  CHANGE_SERVER: "SYS_SERVER",
  RESTART: "SYS_RESTART",
  CHANGE_EM: "SYS_ENERGY",
};

module.exports.REQUEST_COMAND_SOCKET = {
  ADD_TIMER: "ADD_TIMER",
  UPDATE_TIMER: "UPDATE_TIMER",
  DELETE_TIMERS: "DELETE_TIMERS",
  RELAY: "RELAY",
  UPDATE_FIRMWARE: "UPDATE_FIRMWARE",
  SCAN_WIFI: "SCAN_WIFI",
  CONNECT_WIFI: "CONNECT_WIFI",
  CHANGE_SERVER: "CHANGE_SERVER",
  RESTART: "RESTART",
};
module.exports.RESPONSE_COMAND_SOCKET = {
  ADD_TIMER: "SYS_ADD_TIMER",
  UPDATE_TIMER: "SYS_UPDATE_TIMER",
  DELETE_TIMERS: "SYS_DELETE_TIMERS",
  RELAY: "SYS_RELAY",
  UPDATE_FIRMWARE: "SYS_UPDATE_FIRMWARE",
  SCAN_WIFI: "SYS_SCAN_WIFI",
  CONNECT_WIFI: "SYS_CONNECT_WIFI",
  CHANGE_SERVER: "CHANGE_SERVER",
  RESTART: "SYS_RESTART",
};
